website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Bike, User, RentalHistory
from . import db
from datetime import datetime, timedelta

views = Blueprint("views", __name__)

@views.route("/")
@login_required
def home():
    bikes = Bike.query.all()
    return render_template("home.html", user=current_user, bikes=bikes)

@views.route("/profile")
@login_required
def profile():
    user_rentals = current_user.rentals
    owned_bikes = {r.bike for r in user_rentals}
    return render_template("profile.html", user=current_user, user_rentals=user_rentals, owned_bikes=owned_bikes, now=datetime.utcnow())

@views.route("/extend_rental/<int:rental_id>", methods=['POST'])
@login_required
def extend_rental(rental_id):
    rental = RentalHistory.query.get_or_404(rental_id)
    days = int(request.form.get('days', 0))
    cost = days * rental.bike.rental_price

    if current_user.balance < cost:
        flash("Insufficient balance to extend", "error")
        return redirect(url_for('views.profile'))

    current_user.balance -= cost
    rental.return_date += timedelta(days=days)
    rental.payment += cost
    db.session.commit()

    flash("Rental extended successfully", "success")
    return redirect(url_for('views.profile'))

@views.route("/add-balance", methods=['POST'])
@login_required
def add_balance():
    amount = request.form.get('amount', type=float)
    current_user.balance += amount
    db.session.commit()
    flash(f"Balance updated successfully! New balance: ${current_user.balance}", "success")
    return redirect(url_for('views.profile'))

@views.route("/edit_profile", methods=['POST'])
@login_required
def edit_profile():
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if not name or not email:
            flash("Name and email are required", "error")
            return redirect(url_for('views.profile'))
        if password and password != password2:  
            flash("Passwords do not match", "error")
            return redirect(url_for('views.profile'))
        current_user.name = name
        current_user.email = email
        current_user.password = password if password else current_user.password
        db.session.commit()
        flash("Profile updated successfully", "success")
        return redirect(url_for('views.profile'))

@views.route("/Bikes/<bike_name>", methods=['GET', 'POST'])
@login_required
def bike_details(bike_name):
    if request.method == 'POST':
        days = request.form.get('days')
        user_id = current_user.id
        bike = Bike.query.filter_by(name=bike_name).first()
        payment = bike.rental_price * int(days)
        if (current_user.balance < payment):
            flash("Insufficient balance to rent this bike.", category="error")
            return redirect(url_for('views.bike_details', bike_name=bike_name))
        current_user.balance -= payment
        bike_id = bike.id
        rental = RentalHistory(user_id=user_id, bike_id=bike_id, payment=payment, rental_date=datetime.utcnow(), return_date=datetime.utcnow() + timedelta(days=int(days)))
        bike.available = False
        db.session.add(rental)
        db.session.commit()
        flash("Bike rented successfully!", category="success")
        return redirect(url_for('views.home'))

    bike = Bike.query.filter_by(name=bike_name).first()
    if bike:
        return render_template("bike_details.html", user=current_user, bike=bike)
    else:
        flash("Bike not found.", category="error")

@views.route("/manage-bikes")
@login_required
def manage_bikes():
    bikes = Bike.query.all()
    return render_template("bikes_manage.html", user=current_user, bikes=bikes)

@views.route("/delete_bike/<int:bike_id>", methods=['POST'])
@login_required
def delete_bike(bike_id):
    bike = Bike.query.get_or_404(bike_id)
    if bike.available:
        db.session.delete(bike)
        db.session.commit()
        flash("Bike deleted successfully", "success")
        return redirect(url_for('views.manage_bikes'))
    else:
        flash("Cannot delete a rented bike", "error")
        return redirect(url_for('views.manage_bikes'))

@views.route("/modify_bike/<int:bike_id>", methods=['GET', 'POST'])
@login_required
def modify_bike(bike_id):
    bike = Bike.query.get_or_404(bike_id)
    if request.method == 'POST':
        bike.name = request.form.get('name')
        bike.Manufacturer = request.form.get('manufacturer')
        bike.Description = request.form.get('description')        
        bike.rental_price = request.form.get('rental_price', type=float)
        db.session.commit()
        flash("Bike details updated successfully", "success")
        return redirect(url_for('views.manage_bikes'))
    
@views.route("/about")
def about():
    return render_template("AboutUs.html", user=current_user)

@views.route("/contact", methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        message = request.form.get('message')
        if not name or not email or not message:
            flash("All fields are required", "error")
            return redirect(url_for('views.contact'))
        # Here you would typically send the message via email or store it
        flash("Message sent successfully!", "success")
        return redirect(url_for('views.contact'))
    return render_template("ContactUs.html", user=current_user)

website/templates/AboutUs.html
{% extends "base.html" %}

{% block title %} About Us {% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/faq.css') }}">
{% endblock %}

{% block content %}
<div class="faq-container">
  <h2 class="faq-title">FAQs</h2>
  <div class="accordion" id="faqAccordion">
    <div class="faq-item">
        <div class="faq-question">
            <span class="question-text">Is there a charge to opening an account?</span>
            <span class="plus">+</span>
        </div>
        <div class="faq-answer">
            <p>There is no charge associated with opening and maintining an account. There may be overdue charges associated with the account if an item is not returned on the agreed date, but that is all</p>
        </div>
    </div>
    <div class="faq-item">
        <div class="faq-question">
            <span class="question-text">What kinds of bikes can I rent here?</span>
            <span class="plus">+</span>
        </div>
        <div class="faq-answer">
            <p>We have a large variety of bikes that can be selected, from casual city bikes to roam around the city, to electric and off-road bikes for the more veteran and explorative users</p>
        </div>
    </div>
    <div class="faq-item">
        <div class="faq-question">
            <span class="question-text">Am I allowed to rent multiple bikes at once?</span>
            <span class="plus">+</span>
        </div>
        <div class="faq-answer">
            <p>Yes, renting multiple bikes is allowed, and can be rather useful if renting for other people, or bikes for many purposes</p>
        </div>
    </div>
  </div>
</div>
<script>
  document.querySelectorAll('.faq-question').forEach((question) => {
    question.addEventListener('click', () => {
      const item = question.closest('.faq-item');
      const answer = item.querySelector('.faq-answer');

      const isOpen = item.classList.contains('active');

      // Close all
      document.querySelectorAll('.faq-item').forEach((el) => {
        el.classList.remove('active');
        const ans = el.querySelector('.faq-answer');
        ans.style.maxHeight = null;
      });

      // Open clicked if it wasn't already
      if (!isOpen) {
        item.classList.add('active');
        answer.style.maxHeight = answer.scrollHeight + 'px';
      }
    });
  });
</script>
{% endblock %}

website/templates/ContactUs.html
{% extends "base.html" %}

{% block title %}Contact Us{% endblock %}

{% block content %}

<div class="container-xl shadow p-4 my-5 center" style="background-color: #b9b9b9;">
    <h3 align="center">Contact Us</h3>
    <form method="POST">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
        </div>

        <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" name="message" rows="4" placeholder="Enter your message" required></textarea>
        </div>
    </form>
    <button type="submit" class="btn btn-primary">Send Message</button>
</div>

{% endblock %}


website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/baseCSS.css') }}">
    
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"> </span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav ml-auto">
        {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" id="home" href="/"> Home </a>
        <a class="nav-item nav-link" id="profile" href="/profile"> Profile </a>
          {% if current_user.username == 'Admin' or current_user.username == 'Admin1' %}
          <a class="nav-item nav-link" id="addBooks" href="/add-bike"> Add Bike </a>
          <a class="nav-item nav-link" id="manageBikes" href="/manage-bikes"> Manage Bikes </a>
          {% endif %}
        <a class="nav-item nav-link" id="logout" href="/logout"> Logout </a>
        {% else %}
        <a class="nav-item nav-link" id="login" href="/login"> Login </a>
        <a class="nav-item nav-link" id="signUp" href="/sign-up"> Sign Up </a>
        {% endif %}
      </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}
  {% block content %}
  {% endblock %}

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center py-4">
      <p class="text-muted mb-1">
        <a href="/about" class="text-muted mx-2">About Us</a> |
        <a href="/contact" class="text-muted mx-2">Contact</a>
      </p>
      <p class="text-muted mb-1">Follow us on:
        <a href="https://www.facebook.com" target="_blank" class="text-muted"><i class="fa fa-facebook"></i></a>
        <a href="https://www.twitter.com" target="_blank" class="text-muted"><i class="fa fa-twitter"></i></a>
        <a href="https://www.instagram.com" target="_blank" class="text-muted"><i class="fa fa-instagram"></i></a>
      </p>
      <p class="text-muted mb-0">© 2023 Bike Rental Service. All rights reserved.</p>
    </div>
  </footer>

  <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>  
</body>
</html>

website/templates/bike_addition.html
{% extends "base.html" %}

{% block title %} Add Book {% endblock %}

{% block content %}
<div class="container-xl shadow p-4 my-5 center" style="background-color: #b9b9b9;">
<form method="POST">
    <h3 align="center"> Add Bike </h3>
    <div class="form-group">
        <label for="name">Name </label>
        <input type="name" class="form-control" id="name" name="name" placeholder="Enter bike name" required>
    </div>
    <div class="form-group">
        <label for="manufacturer">Manufacturer</label>
        <input type="text" class="form-control" id="manufacturer" name="manufacturer" placeholder="Enter manufacturer name">
    </div>
    <div class="form-group">
        <label for="image_url">image_url</label>
        <input type="text" class="form-control" id="image_url" name="image_url" placeholder="Enter image URL">
    </div>
    <div class="input-group">
        <span class="input-group-text">Description </span>
        <textarea class="form-control" aria-label="With textarea" name="description"></textarea>
    </div>
    <br/>
    <div class="input-group mb-3">
        <span class="input-group-text">$</span>
        <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" name="rental_price" required>
        <span class="input-group-text">.00</span>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary"> Add Bike </button>
</form>
</div>
{% endblock %}

website/templates/bike_details.html
{% extends "base.html" %}

{% block title %} Bike Rent {% endblock %}

{% block content %}

<div class="container-fluid my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card shadow">
        <div class="row g-0">
        
          <div class="col-md-7 p-4">
            <h2>{{ bike.name }}</h2>
            <p class="text-muted">{{ bike.Manufacturer }}</p>
            <p>{{ bike.Description }}</p>
            <p><strong>Price per day:</strong> ${{ "%.2f"|format(bike.rental_price) }}</p>
            <p>
              <strong>Status:</strong>
              {% if bike.available %}
                <span class="badge bg-success">Available</span>
              {% else %}
                <span class="badge bg-secondary">Not Available</span>
              {% endif %}
            </p>
            <p><strong>Estimated cost:</strong>
            <span id="totalCost" name="totalCost"></span></p>
            <p><strong>Return Date:</strong>
            <span id="returnDate"></span></p>



            <form method="POST" class="mt-4">

              <div class="input-group mb-3 w-50">
                <input type="number" id="days" name="days" class="form-control" placeholder="Days to rent" required>
                <button class="btn btn-primary" type="submit" {% if not bike.available %}disabled{% endif %}>
                  Rent Now
                </button>
              </div>
            </form>
          </div>

          <div class="col-md-5">
            <img src="{{ url_for('static', filename='BikePics/' + bike.image_url) }}"
                 class="img-fluid h-100 w-100 rounded-end" style="object-fit: contain;" alt="{{ bike.name }}">
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script>

    const today = new Date();
    const pricePerDay = {{ bike.rental_price|default(0)|tojson }};
    const daysInput = document.getElementById('days');

    function updateCost() {
        const days = parseInt(daysInput.value);
        const totalCost = isNaN(days) ? 0 : days * pricePerDay;
        const ReturnDate = new Date(today);
        ReturnDate.setDate(today.getDate() + days);
        document.getElementById('totalCost').textContent = `$${totalCost.toFixed(2)}`;
        document.getElementById('returnDate').textContent = ReturnDate.toLocaleDateString();
    }

    daysInput.addEventListener('input', updateCost);
    updateCost(); // initial calculation

</script>

{% endblock %}

website/templates/bikes_manage.html
{% extends "base.html" %}

{% block title %} Bikes Management {% endblock %}

{% block content %}

<div class="container-xl my-5">
  <h3 class="text-center mb-4">Available Bikes</h3>
  <div class="table-responsive">
    <table class="table table-secondary align-middle text-center shadow p-3 mb-5 rounded">
      <thead class="table table-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Manufacturer</th>
          <th scope="col">Description</th>
          <th scope="col">Price/Day</th>
          <th scope="col">Status</th>
          <th scope="col">Actions </th>
        </tr>
      </thead>
      <tbody>
        {% for bike in bikes %}
      <form method="POST" action="{{ url_for('views.modify_bike', bike_id=bike.id)}}">
        <tr id="row-{{ bike.id }}">
          <td><input class="form-control" type="text" name="name" value="{{ bike.name }}" readonly></td>
          <td><input class="form-control" type="text" name="manufacturer" value="{{ bike.Manufacturer }}" readonly></td>
          <td><textarea class="form-control" rows="6" name="description" readonly>{{ bike.Description }}</textarea></td>
          <td><input class="form-control" type="number" name="rental_price" value="{{ bike.rental_price }}" step="0.01" readonly></td>
          <td>
            {% if bike.available %}
              <span class="badge bg-success">Available</span>
            {% else %}
              <span class="badge bg-danger">Rented</span>
            {% endif %}
          </td>
          <td>
          
            <div class="d-flex gap-2 mb-3 w-50">
              <button type="submit" class="btn btn-sm mr-2 btn-success d-none" id="save-btn-{{ bike.id }}">Save</button>
            </form>
              <button class="btn btn-sm btn-warning mr-2" onclick="enableEdit({{ bike.id }})">Edit</button>
              <form action="{{ url_for('views.delete_bike', bike_id=bike.id) }}" method="POST" class="form-inline">
                <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this bike?')">Delete</button>
              </form>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  function enableEdit(id) {
  const row = document.getElementById('row-' + id);
  const inputs = row.querySelectorAll('input, textarea');
  inputs.forEach(input => input.removeAttribute('readonly'));

  row.querySelector('.btn-warning').classList.add('d-none');
  document.getElementById(`save-btn-${id}`).classList.remove('d-none');
}
</script>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block head %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container">
    <h1 class="text-center">Welcome to the Bike Rental Service</h1>
    <p class="text-center">Explore our collection of bikes available for rent.</p>
    {% if bikes %}
    <div class="container-lg my-5">
      <h2 class="text-center mb-4">Available Bikes</h2>
      <div class="row justify-content-center">
        {% for bike in bikes %}
        <div class="col-md-4 mb-4">
          <a href="Bikes/{{ bike.name }}" class="text-decoration-none text-dark">
            <div class="card h-150 shadow-sm">
              <img src="{{ url_for('static', filename='BikePics/' + bike.image_url) }}"
                  class="card-img-top" style="height: 200px; object-fit: contain;" alt="{{ bike.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ bike.name }}</h5>
                    <p class="card-text">{{ bike.Manufacturer }}</p>
                </div>
            </div>
          </a>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %} Login  {% endblock %}

{% block content %}
<div class="container-xl shadow p-4 my-5 center">
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="username" class="form-control" id="username" name="username" placeholder="Enter username" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary"> Login </button>
</form>
</div>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block title %} Profile {% endblock %}

{% block content %}

<div class="container-xxl my-5">
  <div class="row">
    
    <!-- Left: Rented Bikes -->
    <div class="col-md-7">
      <h3 class="text-center">Your Rented Bikes</h3>

      {% for bike in owned_bikes %}
      {% set rental = user_rentals | selectattr("bike_id", "equalto", bike.id) | list | first %}
      {% set days_left = (rental.return_date - now).days %}
          <div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mb-3 shadow-sm">
        <div class="row g-0">
          <div class="col-md-4 d-flex align-items-center">
            <img src="{{ url_for('static', filename='BikePics/' + bike.image_url) }}"
                 class="img-fluid rounded-start" alt="{{ bike.name }}">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ bike.name }}</h5>
              <p class="card-text">
                <strong>Days Left:</strong> 
                {% if days_left > 0 %}
                  {{ days_left }} day{{ 's' if days_left != 1 else '' }}
                {% else %}
                  <span class="text-danger">Overdue</span>
                {% endif %}
                <br>
                <strong>Return By:</strong> {{ rental.return_date.strftime("%Y-%m-%d") }} <br>
                <strong>Total Paid: </strong> ${{ "%.2f"|format(rental.payment) }}
                <form action="{{ url_for('views.extend_rental', rental_id=rental.id) }}" method="POST"></form>
                <div class="d-flex gap-2 mb-3 w-50">
                    <input type="number" id="days-{{ loop.index }}" name="days" class="form-control" placeholder="Extend By" required>
                    <button class="btn btn-primary" type="submit">
                      Extend
                    </button>
                </div>
                </form>
                <div id="extraInfo-{{ loop.index }}" class="d-none">
                  <strong>Additional Cost:</strong> <span id="newCost-{{ loop.index }}"></span><br>
                  <strong>New Return Date:</strong> <span id="newReturnDate-{{ loop.index }}"></span>
              </div>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

      <script>
        const payment{{ loop.index }} = {{ rental.payment|default(0)|tojson }};
        const pricePerDay{{ loop.index }} = {{ bike.rental_price|default(0)|tojson }};
        const returnDate{{ loop.index }} = new Date({{ rental.return_date.isoformat()|tojson }});

        const daysInput{{ loop.index }} = document.getElementById('days-{{ loop.index }}');
        const extraInfo{{ loop.index }} = document.getElementById('extraInfo-{{ loop.index }}');
        const newCostSpan{{ loop.index }} = document.getElementById('newCost-{{ loop.index }}');
        const newDateSpan{{ loop.index }} = document.getElementById('newReturnDate-{{ loop.index }}');

          daysInput{{ loop.index }}.addEventListener('input', function () {
          const days = parseInt(this.value);

          if (!isNaN(days) && days > 0) {
            const newCost = pricePerDay{{ loop.index }} * days;
            const newDate = new Date(returnDate{{ loop.index }});
            newDate.setDate(newDate.getDate() + days);

            newCostSpan{{ loop.index }}.textContent = `$${newCost.toFixed(2)}`;
            newDateSpan{{ loop.index }}.textContent = newDate.toLocaleDateString();

            extraInfo{{ loop.index }}.classList.remove('d-none');
          } else {
            extraInfo{{ loop.index }}.classList.add('d-none');
          }
        });
      </script>
      {% endfor %}
    </div>

    <!-- Right: Profile Info -->
    <div class="col-md-5 align-items-center">
      <div class="card mb-3 shadow p-4" style="margin-top: 30px;">
        <h4 class="card-title mb-3">Profile Info</h4>
        <p><strong>Name:</strong> {{ user.username }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Current Balance:</strong> ${{ user.balance }}</p>
        <button class="btn btn-outline-primary mt-3" data-bs-toggle="modal" data-bs-target="#editProfileModal">Edit Profile</a>
        <button class="btn btn-outline-danger mt-3" data-bs-toggle="modal" data-bs-target="#addFundsModal">Add Funds</button>
      </div>
    </div>

  </div>
</div>

<!-- Add Funds Modal -->
<div class="modal fade" id="editProfileModal" tabindex="-1" aria-labelledby="editProfileLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    
      <div class="modal-header">
        <h5 class="modal-title" id="addFundsLabel">Edit Profile</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <form method="POST" action="{{ url_for('views.edit_profile') }}">
        <div class="modal-body">
          <div class="mb-3">
            <label for="username" class="form-label">Name: </label>
            <input type="text" name="name" id="name" class="form-control" value="{{ user.username }}" required>
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Email: </label>
            <input type="text" name="email" id="email" class="form-control" value="{{ user.email }}" required>
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password: </label>
            <input type="password" name="password" id="password" class="form-control" required>
          </div>
            <div class="mb-3">
            <label for="password2" class="form-label">Confirm Password: </label>
            <input type="password" name="password2" id="password2" class="form-control" required>
          </div>
        </div>
        
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Confirm Changes</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </form>
      
    </div>
  </div>
</div>

<div class="modal fade" id="addFundsModal" tabindex="-1" aria-labelledby="addFundsLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    
      <div class="modal-header">
        <h5 class="modal-title" id="addFundsLabel">Add Funds</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <form method="POST" action="{{ url_for('views.add_balance') }}">
        <div class="modal-body">
          <div class="mb-3">
            <label for="amount" class="form-label">Amount ($)</label>
            <input type="number" name="amount" id="amount" class="form-control" min="1" required>
          </div>
        </div>
        
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Add</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </form>
      
    </div>
  </div>
</div>


{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %} Sign Up {% endblock %}

{% block content %}
<div class="container-xl shadow p-4 my-5 center">
    <form method="POST">
        <h3 align="center"> Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="username" class="form-control" id="username" name="username" placeholder="Enter username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <br/>
        <button type="submit" class="btn btn-primary"> Sign Up </button>
    </form>
</div>
{% endblock %}